### ISSUE TITLE
setupFirefox error on firefox browser.

### ISSUE THREAD

**Issue by kingctan** [video-dev/clappr-rtmp-plugin#48]
this.setupFirefox is not a function

please check,thanks.

**Comment by DavidVentura** [comment]
Same here on Firefox 47 on windows. Works on firefox 47 on linux

**Comment by thekrzos** [comment]
Same error on Firefox 47.0.

**Comment by flavioribeiro** [comment]
I merged @tjenkinson's PR regarding this issue, can you guys check if this solves the problem?

**Comment by thekrzos** [comment]
It still doesn`t work. Firefox 47 on Windows 8.1.
TypeError: this.setupFirefox is not a function rtmp.min.js:1:5382
TypeError: t.container is null clappr.min.js:9:5742

**Comment by DavidVentura** [comment]
I had to rollback to previous clappr version, did not test in time, sorry

On 16 June 2016 at 10:27, thekrzos <notifications@github.com> wrote:

> It still doesn`t work. Firefox 47 on Windows 8.1.
> TypeError: this.setupFirefox is not a function rtmp.min.js:1:5382
> TypeError: t.container is null clappr.min.js:9:5742
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/flavioribeiro/clappr-rtmp-plugin/issues/48#issuecomment-226484473>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADe0brbsV32FTC0HnExhY2LbD30Fu4IIks5qMU9cgaJpZM4I0epI>
> .
>



-- 
*Stack* is the new term for "I have no idea what I'm actually using".

**Comment by sarat1669** [comment]
clappr.rtmp is working on chrome, but not on firefox. Can you suggest the player version and rtmp version which work both on chrome and firefox?

**Comment by flavioribeiro** [comment]
I'm reopening this one so I can verify later, @sarat1669. Can you give me a working RTMP source so I can make tests?

**Comment by gfronza** [comment]
@sarat1669 @flavioribeiro Eventials is now running with clappr 0.2.58 and clappr-rtmp-plugin 0.0.13 and it's working fine in all browsers (firefox included).

BaseFlashPlayback _setupFirefox method:
https://github.com/clappr/clappr/blob/master/src/playbacks/base_flash_playback/base_flash_playback.js#L41

RTMP calling _setupFirefox method:
https://github.com/flavioribeiro/clappr-rtmp-plugin/blob/master/src/main.js#L164

@sarat1669 can you provide us a more detailed explanation of the problem you're having in FF?

**Comment by contra** [comment]
I'm seeing the same issue with the latest clappr-rtmp-plugin and clappr. Firefox 56.

**Comment by vdalex25** [comment]
I'm also seeing the same issue with the latest clappr-rtmp-plugin and clappr. 57.0 (64)

**Comment by codenoid** [comment]
pls reopen

```
this._setupFirefox is not a function
```

browser : Mozilla Firefox 61.0.1
code : https://www.w3schools.com/code/tryit.asp?filename=FTFS4KXLTT1C

**Comment by spiritl7db** [comment]
clappr 0.3.12 the lasted version
Firefox 76.0.1
TypeError: this._setupFirefox is not a function
